In [10]:
import yfinance as yf
import pandas as pd
import numpy as np
import random

In [2]:
msft = yf.Ticker("MSFT")
print(msft.info.get('longName'))
print(msft.info.get('sector'))
print(msft.info.get('industry'))
print(msft.fast_info['lastPrice'])

Microsoft Corporation
Technology
Software - Infrastructure
393.1300048828125

In [3]:
tickers_name = pd.read_csv('tickers.csv')
tickers_name

    Ticker
0        A
1       AA
2      ABT
3      ABV
4      ACN
..     ...
500   AKAM
501    TER
502   ENPH
503   FSLR
504   ULTA

[505 rows x 1 columns]

In [4]:
equities = pd.DataFrame(columns=['Ticker', 'Name', 'Sector', 'Industry', 'Last Price'])

In [ ]:
for ticker in tickers_name['Ticker']:
    try:
        stock = yf.Ticker(ticker)
        name = stock.info.get('longName')
        sector = stock.info.get('sector')
        industry = stock.info.get('industry')
        last_price = stock.fast_info['lastPrice']
        
        equities = equities.append({
            'Ticker': ticker,
            'Name': name,
            'Sector': sector,
            'Industry': industry,
            'Last Price': last_price
        }, ignore_index=True)
    except Exception as e:
        print(f"Error fetching data for {ticker}: {e}")

C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$ABV: possibly delisted; no price data found  (period=1y)
$ABV: possibly delisted; no price data found  (period=5d)
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
Exception ignored from cffi callback <function buffer_callback at 0x000002503B10E560>:
Traceback (most recent call last):
  File "c:\Users\Radek\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\curl.py", line 100, in buffer_callback
    @ffi.def_extern()
KeyboardInterrupt:
$ALL: possibly delisted; no price data found  (period=5d)

Error fetching data for ALL: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_14204\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({

In [5]:
equities

Empty DataFrame
Columns: [Ticker, Name, Sector, Industry, Last Price]
Index: []

In [13]:
equities = equities.dropna(how='any').reset_index(drop=True)
equities

,Ticker,Name,Sector,Industry,Last Price
0,A,"Agilent Technologies, Inc.",Healthcare,Diagnostics & Research,136.029999
1,AA,Alcoa Corporation,Basic Materials,Aluminum,47.645
2,ABT,Abbott Laboratories,Healthcare,Medical Devices,89.790001
3,ACN,Accenture plc,Technology,Information Technology Services,138.684998
4,AEM,Agnico Eagle Mines Limited,Basic Materials,Gold,141.154999
...,...,...,...,...,...
466,AKAM,"Akamai Technologies, Inc.",Technology,Software - Infrastructure,120.260002
467,TER,"Teradyne, Inc.",Technology,Semiconductor Equipment & Materials,338.590302
468,ENPH,"Enphase Energy, Inc.",Technology,Solar,43.830002
469,FSLR,"First Solar, Inc.",Technology,Solar,223.279999
470,ULTA,"Ulta Beauty, Inc.",Consumer Cyclical,Specialty Retail,472.519989

In [203]:
equities.to_csv("equities.csv", index=False)

In [204]:
equities_list = equities['Ticker'].to_list()

In [215]:
prices = yf.download(
    equities_list,
    period="5y",
    auto_adjust=True
)

prices_raw = prices.copy()

[*********************100%***********************]  449 of 449 completed

1 Failed download:
['BK']: YFPricesMissingError('possibly delisted; no price data found  (period=5y)')

In [206]:
prices_raw = prices_raw.dropna(how = "all")
prices_raw = prices_raw.dropna(axis = 1,how = "all")
prices_raw = prices_raw.fillna(prices_raw.mean())

In [207]:
prices = prices_raw['Close']

In [208]:
returns = prices.pct_change()
returns

Ticker,A,AA,AAPL,ABT,ACN,ADI,ADP,ADSK,AEM,AEP,...,WY,WYNN,XEL,XOM,XYL,YUM,ZBH,ZG,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2021-07-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-07-19,-0.009065,-0.040364,-0.026915,0.010893,-0.008753,-0.009100,-0.019066,-0.020523,-0.008978,-0.019659,...,-0.031452,0.000382,-0.012440,-0.034368,-0.017845,-0.020716,-0.021056,0.006439,-0.038306,-0.009265
2021-07-20,0.011655,0.105313,0.025974,-0.000505,0.009315,0.012140,0.007239,0.030664,0.004118,-0.000350,...,0.021244,0.017472,-0.001611,0.011021,0.036680,0.023887,0.036359,0.025120,0.052411,0.012805
2021-07-21,-0.002344,0.061230,-0.005132,0.002106,0.005479,0.024424,0.006547,0.019114,0.003609,-0.011897,...,0.012779,0.028338,-0.016138,0.032166,0.007406,0.005252,0.025316,0.034233,0.028685,-0.010344
2021-07-22,0.009064,0.003775,0.009629,-0.006136,0.001562,-0.017107,-0.005771,0.022301,-0.013076,0.001889,...,0.002641,-0.019984,0.002684,-0.011253,-0.003512,0.029888,-0.005703,-0.010560,-0.025562,0.012624
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-10,0.005240,-0.000821,-0.002846,-0.004979,-0.027542,0.005106,0.002653,-0.000623,-0.014494,0.011804,...,0.042222,0.009511,0.013161,0.010330,0.019598,0.007082,0.023647,-0.036435,0.009140,0.006393
2026-07-13,-0.001862,0.000822,0.006311,-0.019376,0.024329,-0.024365,0.037740,0.018086,-0.022877,0.001477,...,-0.001706,-0.026461,0.005246,0.040539,-0.000083,-0.011373,0.029998,-0.001875,-0.004246,-0.002250
2026-07-14,0.008654,0.006979,-0.007721,-0.034198,-0.028588,0.017461,-0.018363,-0.029686,0.006271,-0.005087,...,0.016660,-0.012663,-0.003852,0.004014,0.002805,-0.021648,-0.032419,-0.004383,0.000853,-0.017509
2026-07-15,-0.003624,-0.009784,0.040145,0.010642,0.018282,-0.004558,0.004180,0.014860,-0.015096,-0.018082,...,0.004622,0.011992,-0.011476,-0.003998,-0.000987,-0.035466,-0.009777,0.061006,0.016047,0.006210
2026-07-16,-0.002821,-0.043434,0.009084,0.109555,0.046052,-0.029952,0.035115,0.032108,-0.035084,0.003623,...,0.027394,0.015250,0.008517,0.010103,0.030800,-0.002229,0.029066,-0.001482,0.021593,0.035892

In [209]:
returns = returns.dropna(how = "all")

In [210]:
returns.isna().sum().sum()

0

In [211]:
log_returns = np.log(prices / prices.shift(1))

In [213]:
log_return = log_returns.dropna(how = "all")

In [214]:
log_returns.isna().sum().sum()

448

In [39]:
log_returns

Ticker,A,AA,AAPL,ABT,ACN,ADI,ADP,ADSK,AEM,AEP,...,WY,WYNN,XEL,XOM,XYL,YUM,ZBH,ZG,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2021-07-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-07-16,-0.000202,-0.047127,-0.014176,0.007260,-0.009668,-0.019871,-0.006931,-0.004965,-0.021319,0.003549,...,-0.017772,-0.033160,0.005948,-0.028040,-0.005431,-0.009792,0.001958,-0.006324,-0.040887,-0.002801
2021-07-19,-0.009106,-0.041202,-0.027283,0.010834,-0.008791,-0.009142,-0.019250,-0.020736,-0.009019,-0.019855,...,-0.031957,0.000382,-0.012518,-0.034973,-0.018006,-0.020934,-0.021281,0.006418,-0.039059,-0.009308
2021-07-20,0.011587,0.100129,0.025643,-0.000505,0.009272,0.012067,0.007213,0.030203,0.004109,-0.000350,...,0.021022,0.017321,-0.001613,0.010961,0.036023,0.023606,0.035714,0.024810,0.051083,0.012724
2021-07-21,-0.002347,0.059429,-0.005145,0.002103,0.005465,0.024130,0.006526,0.018934,0.003602,-0.011968,...,0.012698,0.027944,-0.016270,0.031659,0.007378,0.005238,0.025001,0.033660,0.028282,-0.010398
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-09,0.034420,0.004320,0.008990,-0.008229,0.025491,0.021155,-0.000373,0.012252,0.028173,-0.015199,...,0.001779,0.009148,-0.007564,-0.026348,0.002274,-0.017459,0.018893,0.033061,0.019905,-0.000266
2026-07-10,0.005226,-0.000821,-0.002850,-0.004991,-0.027928,0.005093,0.002649,-0.000623,-0.014600,0.011735,...,0.041355,0.009466,0.013075,0.010277,0.019408,0.007057,0.023371,-0.037115,0.009099,0.006373
2026-07-13,-0.001863,0.000821,0.006291,-0.019566,0.024038,-0.024667,0.037045,0.017924,-0.023143,0.001476,...,-0.001707,-0.026817,0.005232,0.039738,-0.000083,-0.011439,0.029557,-0.001877,-0.004255,-0.002252
2026-07-14,0.008617,0.006954,-0.007751,-0.034797,-0.029005,0.017310,-0.018534,-0.030136,0.006252,-0.005100,...,0.016522,-0.012744,-0.003859,0.004006,0.002801,-0.021885,-0.032956,-0.004393,0.000852,-0.017664
2026-07-15,-0.003185,-0.019762,0.037297,-0.002082,0.026330,-0.011112,0.003443,0.011732,-0.018521,-0.011627,...,0.008993,0.011456,-0.009399,-0.014160,-0.003709,-0.023410,-0.004514,0.052228,0.019268,0.004580

In [40]:
log_returns.to_csv("log_returns_daily.csv", index=True)

In [3]:
log_returns = pd.read_csv("log_returns_daily.csv", index_col=0, parse_dates=True)

In [4]:
equities = pd.read_csv("equities.csv")

In [199]:
equities

,Ticker,Name,Sector,Industry,Last Price
254,NWL,Newell Brands Inc.,Consumer Defensive,Household & Personal Products,5.270000
214,LUMN,"Lumen Technologies, Inc.",Communication Services,Telecom Services,6.445000
336,UA,"Under Armour, Inc.",Consumer Cyclical,Apparel Manufacturing,6.905000
337,UAA,"Under Armour, Inc.",Consumer Cyclical,Apparel Manufacturing,7.075000
82,CRT,Cross Timbers Royalty Trust,Energy,Oil & Gas E&P,9.260000
...,...,...,...,...,...
244,MTD,Mettler-Toledo International Inc.,Healthcare,Diagnostics & Research,1329.089966
239,MPWR,"Monolithic Power Systems, Inc.",Technology,Semiconductors,1341.479980
414,ASML,ASML Holding N.V.,Technology,Semiconductor Equipment & Materials,1777.084961
411,MELI,"MercadoLibre, Inc.",Consumer Cyclical,Internet Retail,1851.500000
232,MKL,Markel Group Inc.,Financial Services,Insurance - Property & Casualty,1933.520020

In [31]:
equities.sort_values(by='Last Price', inplace=True)

In [12]:
random.choice(equities['Ticker'])

'ULTA'

In [41]:
def portfolio_generator(positions, equities_df):
    portfolio_data = []
    for _ in range(positions):
        ticker = random.choice(equities_df['Ticker'])
        number_of_shares = random.randint(10000, 50000)
        equity = equities_df[equities_df['Ticker'] == ticker].iloc[0]
        
        portfolio_data.append({
            'Ticker': ticker,
            'Name': equity['Name'],
            'Sector': equity['Sector'],
            'Industry': equity['Industry'],
            'Number of shares': number_of_shares,
            'Price': equity['Last Price'],
            'Position Value': number_of_shares * equity['Last Price']
        })
    
    return pd.DataFrame(portfolio_data)

In [177]:
portfolio = portfolio_generator(1000, equities)

In [178]:
portfolio

,Ticker,Name,Sector,Industry,Number of shares,Price,Position Value
0,CB,Chubb Limited,Financial Services,Insurance - Property & Casualty,46518,339.220001,1.577984e+07
1,UAL,"United Airlines Holdings, Inc.",Industrials,Airlines,48924,121.839996,5.960900e+06
2,EQR,Equity Residential,Real Estate,REIT - Residential,41420,68.639999,2.843069e+06
3,COST,Costco Wholesale Corporation,Consumer Defensive,Discount Stores,49309,922.205017,4.547301e+07
4,LOW,"Lowe's Companies, Inc.",Consumer Cyclical,Home Improvement Retail,37221,211.175003,7.860145e+06
...,...,...,...,...,...,...,...
995,EMN,Eastman Chemical Company,Basic Materials,Specialty Chemicals,41910,68.029999,2.851137e+06
996,CSCO,"Cisco Systems, Inc.",Technology,Communication Equipment,21594,111.160004,2.400389e+06
997,CNH,CNH Industrial N.V.,Industrials,Farm & Heavy Construction Machinery,29731,10.515000,3.126215e+05
998,CRWD,"CrowdStrike Holdings, Inc.",Technology,Software - Infrastructure,49193,206.464996,1.015663e+07
999,FITB,Fifth Third Bancorp,Financial Services,Banks - Regional,33385,58.064999,1.938500e+06

In [179]:
portfolio = portfolio.groupby('Ticker', as_index=False).agg({
    'Name': 'first',
    'Sector': 'first',
    'Industry': 'first',
    'Number of shares': 'sum',
    'Position Value': 'sum'
})

portfolio['Price'] = portfolio['Position Value'] / portfolio['Number of shares']
portfolio = portfolio[['Ticker', 'Name', 'Sector', 'Industry', 'Number of shares', 'Price', 'Position Value']]

In [180]:
portfolio

,Ticker,Name,Sector,Industry,Number of shares,Price,Position Value
0,AAPL,Apple Inc.,Technology,Consumer Electronics,40960,326.890015,1.338942e+07
1,ABT,Abbott Laboratories,Healthcare,Medical Devices,83717,89.790001,7.516950e+06
2,ACN,Accenture plc,Technology,Information Technology Services,64383,138.684998,8.928956e+06
3,ADI,"Analog Devices, Inc.",Technology,Semiconductors,53884,387.970001,2.090538e+07
4,ADP,"Automatic Data Processing, Inc.",Technology,Software - Application,50423,248.714996,1.254096e+07
...,...,...,...,...,...,...,...
391,XYL,Xylem Inc.,Industrials,Specialty Industrial Machinery,23888,120.940002,2.889015e+06
392,ZBH,"Zimmer Biomet Holdings, Inc.",Healthcare,Medical Devices,219524,91.540001,2.009523e+07
393,ZG,"Zillow Group, Inc.",Communication Services,Internet Content & Information,188000,33.924999,6.377900e+06
394,ZION,"Zions Bancorporation, National Association",Financial Services,Banks - Regional,86518,71.660004,6.199880e+06
395,ZTS,Zoetis Inc.,Healthcare,Drug Manufacturers - Specialty & Generic,264067,74.754997,1.974033e+07

In [181]:
portfolio['Weight'] = portfolio['Position Value'] / portfolio['Position Value'].sum()

In [182]:
log_returns

,A,AA,AAPL,ABT,ACN,ADI,ADP,ADSK,AEM,AEP,...,WY,WYNN,XEL,XOM,XYL,YUM,ZBH,ZG,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2021-07-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-07-16,-0.000202,-0.047127,-0.014176,0.007260,-0.009668,-0.019871,-0.006931,-0.004965,-0.021319,0.003549,...,-0.017772,-0.033160,0.005948,-0.028040,-0.005431,-0.009792,0.001958,-0.006324,-0.040887,-0.002801
2021-07-19,-0.009106,-0.041202,-0.027283,0.010834,-0.008791,-0.009142,-0.019250,-0.020736,-0.009019,-0.019855,...,-0.031957,0.000382,-0.012518,-0.034973,-0.018006,-0.020934,-0.021281,0.006418,-0.039059,-0.009308
2021-07-20,0.011587,0.100129,0.025643,-0.000505,0.009272,0.012067,0.007213,0.030203,0.004109,-0.000350,...,0.021022,0.017321,-0.001613,0.010961,0.036023,0.023606,0.035714,0.024810,0.051083,0.012724
2021-07-21,-0.002347,0.059429,-0.005145,0.002103,0.005465,0.024130,0.006526,0.018934,0.003602,-0.011968,...,0.012698,0.027944,-0.016270,0.031659,0.007378,0.005238,0.025001,0.033660,0.028282,-0.010398
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-09,0.034420,0.004320,0.008990,-0.008229,0.025491,0.021155,-0.000373,0.012252,0.028173,-0.015199,...,0.001779,0.009148,-0.007564,-0.026348,0.002274,-0.017459,0.018893,0.033061,0.019905,-0.000266
2026-07-10,0.005226,-0.000821,-0.002850,-0.004991,-0.027928,0.005093,0.002649,-0.000623,-0.014600,0.011735,...,0.041355,0.009466,0.013075,0.010277,0.019408,0.007057,0.023371,-0.037115,0.009099,0.006373
2026-07-13,-0.001863,0.000821,0.006291,-0.019566,0.024038,-0.024667,0.037045,0.017924,-0.023143,0.001476,...,-0.001707,-0.026817,0.005232,0.039738,-0.000083,-0.011439,0.029557,-0.001877,-0.004255,-0.002252
2026-07-14,0.008617,0.006954,-0.007751,-0.034797,-0.029005,0.017310,-0.018534,-0.030136,0.006252,-0.005100,...,0.016522,-0.012744,-0.003859,0.004006,0.002801,-0.021885,-0.032956,-0.004393,0.000852,-0.017664
2026-07-15,-0.003185,-0.019762,0.037297,-0.002082,0.026330,-0.011112,0.003443,0.011732,-0.018521,-0.011627,...,0.008993,0.011456,-0.009399,-0.014160,-0.003709,-0.023410,-0.004514,0.052228,0.019268,0.004580

In [188]:
selected_log_returns = log_returns.loc[:, log_returns.columns.isin(portfolio['Ticker'])]
selected_log_returns

,AAPL,ABT,ACN,ADI,ADP,ADSK,AEM,AEP,AER,AES,...,WMT,WST,WYNN,XEL,XOM,XYL,ZBH,ZG,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2021-07-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-07-16,-0.014176,0.007260,-0.009668,-0.019871,-0.006931,-0.004965,-0.021319,0.003549,-0.016621,-0.008990,...,-0.000706,0.004560,-0.033160,0.005948,-0.028040,-0.005431,0.001958,-0.006324,-0.040887,-0.002801
2021-07-19,-0.027283,0.010834,-0.008791,-0.009142,-0.019250,-0.020736,-0.009019,-0.019855,-0.039891,-0.032544,...,-0.002334,-0.007144,0.000382,-0.012518,-0.034973,-0.018006,-0.021281,0.006418,-0.039059,-0.009308
2021-07-20,0.025643,-0.000505,0.009272,0.012067,0.007213,0.030203,0.004109,-0.000350,0.056120,0.021813,...,0.004521,0.005003,0.017321,-0.001613,0.010961,0.036023,0.035714,0.024810,0.051083,0.012724
2021-07-21,-0.005145,0.002103,0.005465,0.024130,0.006526,0.018934,0.003602,-0.011968,0.039643,0.010730,...,-0.004946,-0.012800,0.027944,-0.016270,0.031659,0.007378,0.025001,0.033660,0.028282,-0.010398
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-09,0.008990,-0.008229,0.025491,0.021155,-0.000373,0.012252,0.028173,-0.015199,0.014002,0.006129,...,-0.007900,0.011190,0.009148,-0.007564,-0.026348,0.002274,0.018893,0.033061,0.019905,-0.000266
2026-07-10,-0.002850,-0.004991,-0.027928,0.005093,0.002649,-0.000623,-0.014600,0.011735,-0.007710,0.003389,...,0.014949,-0.011105,0.009466,0.013075,0.010277,0.019408,0.023371,-0.037115,0.009099,0.006373
2026-07-13,0.006291,-0.019566,0.024038,-0.024667,0.037045,0.017924,-0.023143,0.001476,-0.004883,-0.001354,...,0.007696,0.016793,-0.026817,0.005232,0.039738,-0.000083,0.029557,-0.001877,-0.004255,-0.002252
2026-07-14,-0.007751,-0.034797,-0.029005,0.017310,-0.018534,-0.030136,0.006252,-0.005100,-0.016155,0.002706,...,-0.009454,-0.005716,-0.012744,-0.003859,0.004006,0.002801,-0.032956,-0.004393,0.000852,-0.017664
2026-07-15,0.037297,-0.002082,0.026330,-0.011112,0.003443,0.011732,-0.018521,-0.011627,0.003843,0.000338,...,0.002109,0.005716,0.011456,-0.009399,-0.014160,-0.003709,-0.004514,0.052228,0.019268,0.004580

In [184]:
portfolio['Weight'].shape

(396,)

In [189]:
selected_log_returns = selected_log_returns.dropna(how = "all")

In [ ]:
selected_log_returns = selected_log_returns.dropna(how = "all")
selected_log_returns = selected_log_returns.dropna(axis = 1,how = "all")
selected_log_returns = selected_log_returns.fillna(selected_log_returns.mean())

In [195]:
selected_log_returns = selected_log_returns.fillna(selected_log_returns.mean())

In [196]:
selected_log_returns

,AAPL,ABT,ACN,ADI,ADP,ADSK,AEM,AEP,AER,AES,...,WMT,WST,WYNN,XEL,XOM,XYL,ZBH,ZG,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2021-07-16,-0.014176,0.007260,-0.009668,-0.019871,-0.006931,-0.004965,-0.021319,0.003549,-0.016621,-0.008990,...,-0.000706,0.004560,-0.033160,0.005948,-0.028040,-0.005431,0.001958,-0.006324,-0.040887,-0.002801
2021-07-19,-0.027283,0.010834,-0.008791,-0.009142,-0.019250,-0.020736,-0.009019,-0.019855,-0.039891,-0.032544,...,-0.002334,-0.007144,0.000382,-0.012518,-0.034973,-0.018006,-0.021281,0.006418,-0.039059,-0.009308
2021-07-20,0.025643,-0.000505,0.009272,0.012067,0.007213,0.030203,0.004109,-0.000350,0.056120,0.021813,...,0.004521,0.005003,0.017321,-0.001613,0.010961,0.036023,0.035714,0.024810,0.051083,0.012724
2021-07-21,-0.005145,0.002103,0.005465,0.024130,0.006526,0.018934,0.003602,-0.011968,0.039643,0.010730,...,-0.004946,-0.012800,0.027944,-0.016270,0.031659,0.007378,0.025001,0.033660,0.028282,-0.010398
2021-07-22,0.009583,-0.006154,0.001560,-0.017255,-0.005788,0.022056,-0.013162,0.001887,-0.028904,-0.014056,...,0.000708,0.016255,-0.020186,0.002681,-0.011317,-0.003518,-0.005719,-0.010616,-0.025894,0.012545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-09,0.008990,-0.008229,0.025491,0.021155,-0.000373,0.012252,0.028173,-0.015199,0.014002,0.006129,...,-0.007900,0.011190,0.009148,-0.007564,-0.026348,0.002274,0.018893,0.033061,0.019905,-0.000266
2026-07-10,-0.002850,-0.004991,-0.027928,0.005093,0.002649,-0.000623,-0.014600,0.011735,-0.007710,0.003389,...,0.014949,-0.011105,0.009466,0.013075,0.010277,0.019408,0.023371,-0.037115,0.009099,0.006373
2026-07-13,0.006291,-0.019566,0.024038,-0.024667,0.037045,0.017924,-0.023143,0.001476,-0.004883,-0.001354,...,0.007696,0.016793,-0.026817,0.005232,0.039738,-0.000083,0.029557,-0.001877,-0.004255,-0.002252
2026-07-14,-0.007751,-0.034797,-0.029005,0.017310,-0.018534,-0.030136,0.006252,-0.005100,-0.016155,0.002706,...,-0.009454,-0.005716,-0.012744,-0.003859,0.004006,0.002801,-0.032956,-0.004393,0.000852,-0.017664
2026-07-15,0.037297,-0.002082,0.026330,-0.011112,0.003443,0.011732,-0.018521,-0.011627,0.003843,0.000338,...,0.002109,0.005716,0.011456,-0.009399,-0.014160,-0.003709,-0.004514,0.052228,0.019268,0.004580

In [197]:
selected_log_returns.isna().sum().sum()

0

In [76]:
calculate_historical_portfolio_returns = selected_log_returns.mul(portfolio['Weight'].values, axis=1).sum(axis=1)

In [78]:
calculate_historical_portfolio_returns.sort_values()

Date
2025-04-04   -0.060662
2025-04-03   -0.050620
2022-09-13   -0.041460
2022-06-13   -0.040861
2022-05-18   -0.039800
                ...
2022-06-24    0.032352
2025-05-12    0.032581
2022-10-04    0.033577
2022-11-10    0.056617
2025-04-09    0.084559
Length: 1255, dtype: float64

In [86]:
Var_95 = np.quantile(calculate_historical_portfolio_returns, 0.05) * portfolio['Position Value'].sum()
Var_97_5 = np.quantile(calculate_historical_portfolio_returns, 0.025) * portfolio['Position Value'].sum()
Var_99 = np.quantile(calculate_historical_portfolio_returns, 0.01) * portfolio['Position Value'].sum()
Var_99_97 = np.quantile(calculate_historical_portfolio_returns, 0.0001)* portfolio['Position Value'].sum()

In [87]:
Var_99

-165312070.21559072

In [88]:
Var_99_97

-335317672.2271942

In [172]:
selected_log_returns = selected_log_returns.dropna(axis=1, how='any')

In [ ]:
selected_log_returns.shape

Empty DataFrame
Columns: []
Index: [2021-07-15 00:00:00, 2021-07-16 00:00:00, 2021-07-19 00:00:00, 2021-07-20 00:00:00, 2021-07-21 00:00:00, 2021-07-22 00:00:00, 2021-07-23 00:00:00, 2021-07-26 00:00:00, 2021-07-27 00:00:00, 2021-07-28 00:00:00, 2021-07-29 00:00:00, 2021-07-30 00:00:00, 2021-08-02 00:00:00, 2021-08-03 00:00:00, 2021-08-04 00:00:00, 2021-08-05 00:00:00, 2021-08-06 00:00:00, 2021-08-09 00:00:00, 2021-08-10 00:00:00, 2021-08-11 00:00:00, 2021-08-12 00:00:00, 2021-08-13 00:00:00, 2021-08-16 00:00:00, 2021-08-17 00:00:00, 2021-08-18 00:00:00, 2021-08-19 00:00:00, 2021-08-20 00:00:00, 2021-08-23 00:00:00, 2021-08-24 00:00:00, 2021-08-25 00:00:00, 2021-08-26 00:00:00, 2021-08-27 00:00:00, 2021-08-30 00:00:00, 2021-08-31 00:00:00, 2021-09-01 00:00:00, 2021-09-02 00:00:00, 2021-09-03 00:00:00, 2021-09-07 00:00:00, 2021-09-08 00:00:00, 2021-09-09 00:00:00, 2021-09-10 00:00:00, 2021-09-13 00:00:00, 2021-09-14 00:00:00, 2021-09-15 00:00:00, 2021-09-16 00:00:00, 2021-09-17 00:00:00, 2021-09-20 00:00:00, 2021-09-21 00:00:00, 2021-09-22 00:00:00, 2021-09-23 00:00:00, 2021-09-24 00:00:00, 2021-09-27 00:00:00, 2021-09-28 00:00:00, 2021-09-29 00:00:00, 2021-09-30 00:00:00, 2021-10-01 00:00:00, 2021-10-04 00:00:00, 2021-10-05 00:00:00, 2021-10-06 00:00:00, 2021-10-07 00:00:00, 2021-10-08 00:00:00, 2021-10-11 00:00:00, 2021-10-12 00:00:00, 2021-10-13 00:00:00, 2021-10-14 00:00:00, 2021-10-15 00:00:00, 2021-10-18 00:00:00, 2021-10-19 00:00:00, 2021-10-20 00:00:00, 2021-10-21 00:00:00, 2021-10-22 00:00:00, 2021-10-25 00:00:00, 2021-10-26 00:00:00, 2021-10-27 00:00:00, 2021-10-28 00:00:00, 2021-10-29 00:00:00, 2021-11-01 00:00:00, 2021-11-02 00:00:00, 2021-11-03 00:00:00, 2021-11-04 00:00:00, 2021-11-05 00:00:00, 2021-11-08 00:00:00, 2021-11-09 00:00:00, 2021-11-10 00:00:00, 2021-11-11 00:00:00, 2021-11-12 00:00:00, 2021-11-15 00:00:00, 2021-11-16 00:00:00, 2021-11-17 00:00:00, 2021-11-18 00:00:00, 2021-11-19 00:00:00, 2021-11-22 00:00:00, 2021-11-23 00:00:00, 2021-11-24 00:00:00, 2021-11-26 00:00:00, 2021-11-29 00:00:00, 2021-11-30 00:00:00, 2021-12-01 00:00:00, 2021-12-02 00:00:00, 2021-12-03 00:00:00, ...]

[1255 rows x 0 columns]

In [108]:
covariance = selected_log_returns.cov()
covariance

,ABT,ACN,ADI,ADP,ADSK,AEP,AER,AES,AFL,AIG,...,WMT,WST,WY,WYNN,XEL,XYL,YUM,ZBH,ZG,ZION
ABT,0.000199,0.000089,0.000072,0.000081,0.000097,0.000062,0.000071,0.000071,0.000060,0.000065,...,0.000042,0.000100,0.000081,0.000062,0.000060,0.000079,0.000067,0.000098,0.000094,0.000080
ACN,0.000089,0.000372,0.000131,0.000153,0.000226,0.000035,0.000119,0.000099,0.000081,0.000100,...,0.000046,0.000132,0.000109,0.000143,0.000042,0.000121,0.000077,0.000085,0.000197,0.000149
ADI,0.000072,0.000131,0.000448,0.000092,0.000199,0.000025,0.000202,0.000155,0.000070,0.000105,...,0.000051,0.000140,0.000143,0.000232,0.000032,0.000171,0.000084,0.000102,0.000222,0.000205
ADP,0.000081,0.000153,0.000092,0.000200,0.000158,0.000051,0.000075,0.000075,0.000080,0.000089,...,0.000045,0.000095,0.000085,0.000089,0.000054,0.000095,0.000070,0.000076,0.000145,0.000123
ADSK,0.000097,0.000226,0.000199,0.000158,0.000503,0.000025,0.000163,0.000131,0.000075,0.000105,...,0.000062,0.000163,0.000130,0.000215,0.000035,0.000160,0.000092,0.000105,0.000362,0.000182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XYL,0.000079,0.000121,0.000171,0.000095,0.000160,0.000056,0.000147,0.000142,0.000085,0.000110,...,0.000054,0.000113,0.000123,0.000148,0.000054,0.000273,0.000082,0.000100,0.000206,0.000168
YUM,0.000067,0.000077,0.000084,0.000070,0.000092,0.000053,0.000086,0.000095,0.000066,0.000078,...,0.000048,0.000074,0.000083,0.000097,0.000052,0.000082,0.000169,0.000071,0.000110,0.000071
ZBH,0.000098,0.000085,0.000102,0.000076,0.000105,0.000058,0.000111,0.000105,0.000070,0.000099,...,0.000039,0.000094,0.000106,0.000113,0.000058,0.000100,0.000071,0.000296,0.000117,0.000118
ZG,0.000094,0.000197,0.000222,0.000145,0.000362,0.000031,0.000193,0.000190,0.000055,0.000099,...,0.000045,0.000191,0.000185,0.000307,0.000041,0.000206,0.000110,0.000117,0.001096,0.000229
ZION,0.000080,0.000149,0.000205,0.000123,0.000182,0.000046,0.000247,0.000179,0.000160,0.000245,...,0.000047,0.000104,0.000184,0.000250,0.000047,0.000168,0.000071,0.000118,0.000229,0.000731

In [97]:
portfolio['Weight'].shape

(391,)

In [98]:
covariance.shape

(391, 391)

In [111]:
portfolio

,Ticker,Name,Sector,Industry,Number of shares,Price,Position Value,Weight
0,ABT,Abbott Laboratories,Healthcare,Medical Devices,37477,89.790001,3.365060e+06,0.000596
1,ACN,Accenture plc,Technology,Information Technology Services,183949,138.684998,2.551097e+07,0.004519
2,ADI,"Analog Devices, Inc.",Technology,Semiconductors,97662,387.970001,3.788993e+07,0.006712
3,ADP,"Automatic Data Processing, Inc.",Technology,Software - Application,109657,248.714996,2.727334e+07,0.004832
4,ADSK,"Autodesk, Inc.",Technology,Software - Application,39667,208.839996,8.284056e+06,0.001468
...,...,...,...,...,...,...,...,...
386,XYL,Xylem Inc.,Industrials,Specialty Industrial Machinery,129068,120.940002,1.560948e+07,0.002765
387,YUM,"Yum! Brands, Inc.",Consumer Cyclical,Restaurants,61302,154.764999,9.487404e+06,0.001681
388,ZBH,"Zimmer Biomet Holdings, Inc.",Healthcare,Medical Devices,147091,91.540001,1.346471e+07,0.002385
389,ZG,"Zillow Group, Inc.",Communication Services,Internet Content & Information,21495,33.924999,7.292179e+05,0.000129
390,ZION,"Zions Bancorporation, National Association",Financial Services,Banks - Regional,38268,71.660004,2.742285e+06,0.000486

In [110]:
# Align weights with covariance matrix columns
weights_aligned = portfolio.set_index('Ticker')['Weight'].reindex(covariance.columns).fillna(0).values

portfolio_variance = weights_aligned.T @ covariance.values @ weights_aligned
portfolio_volatility = np.sqrt(portfolio_variance)

print(f"Portfolio Variance: {portfolio_variance:.6f}")
print(f"Portfolio Volatility: {portfolio_volatility:.6f}")

Portfolio Variance: nan
Portfolio Volatility: nan

In [106]:
portfolio_variance = portfolio['Weight'].values.T @ covariance.values @ portfolio['Weight'].values
portfolio_volatility = np.sqrt(portfolio_variance)

print(portfolio_volatility)

nan

In [133]:
portfolio = portfolio.set_index('Ticker')

In [134]:
portfolio

,Name,Sector,Industry,Number of shares,Price,Position Value,Weight
Ticker,,,,,,,
ABT,Abbott Laboratories,Healthcare,Medical Devices,37477,89.790001,3.365060e+06,0.000596
ACN,Accenture plc,Technology,Information Technology Services,183949,138.684998,2.551097e+07,0.004519
ADI,"Analog Devices, Inc.",Technology,Semiconductors,97662,387.970001,3.788993e+07,0.006712
ADP,"Automatic Data Processing, Inc.",Technology,Software - Application,109657,248.714996,2.727334e+07,0.004832
ADSK,"Autodesk, Inc.",Technology,Software - Application,39667,208.839996,8.284056e+06,0.001468
...,...,...,...,...,...,...,...
XYL,Xylem Inc.,Industrials,Specialty Industrial Machinery,129068,120.940002,1.560948e+07,0.002765
YUM,"Yum! Brands, Inc.",Consumer Cyclical,Restaurants,61302,154.764999,9.487404e+06,0.001681
ZBH,"Zimmer Biomet Holdings, Inc.",Healthcare,Medical Devices,147091,91.540001,1.346471e+07,0.002385
ZG,"Zillow Group, Inc.",Communication Services,Internet Content & Information,21495,33.924999,7.292179e+05,0.000129
ZION,"Zions Bancorporation, National Association",Financial Services,Banks - Regional,38268,71.660004,2.742285e+06,0.000486

In [136]:
weights = portfolio['Weight']
weights

Ticker
ABT     0.000596
ACN     0.004519
ADI     0.006712
ADP     0.004832
ADSK    0.001468
          ...
XYL     0.002765
YUM     0.001681
ZBH     0.002385
ZG      0.000129
ZION    0.000486
Name: Weight, Length: 391, dtype: float64

In [142]:
weights.values.T

array([5.96131250e-04, 4.51935033e-03, 6.71232311e-03, 4.83156055e-03,
       1.46754737e-03, 1.58490522e-03, 3.69939655e-03, 2.12397025e-04,
       2.35923072e-03, 6.03605036e-04, 3.34461469e-03, 3.12583133e-03,
       2.32911006e-03, 9.15610119e-04, 1.79365845e-03, 6.12892660e-04,
       8.39091303e-05, 2.60442214e-03, 1.55804443e-03, 2.19441255e-03,
       5.11744202e-03, 7.43317176e-03, 7.14839424e-04, 9.52552516e-04,
       2.93279920e-03, 2.74430179e-03, 7.41218526e-04, 7.02794286e-04,
       2.86294986e-04, 2.28142690e-04, 2.11575479e-02, 5.48556863e-03,
       1.60380518e-03, 6.33658096e-03, 2.88660677e-03, 1.53274490e-03,
       3.35497516e-03, 4.31066821e-03, 6.64325969e-03, 9.84057689e-04,
       1.76116747e-04, 7.13496274e-04, 1.13637486e-03, 2.60914558e-03,
       1.00648987e-03, 6.01358444e-04, 8.26062776e-03, 2.41294420e-03,
       3.21880085e-03, 1.94690606e-03, 7.15451272e-03, 2.56751099e-03,
       1.02784357e-03, 1.74351177e-03, 8.94847949e-04, 6.06289172e-04,
       1.96982772e-03, 3.18849307e-03, 1.74394511e-04, 4.42532898e-03,
       7.96124272e-04, 2.64053013e-03, 6.31273217e-04, 1.46207256e-03,
       2.22671806e-03, 3.82152845e-04, 6.21386449e-03, 1.35334233e-03,
       1.19593693e-03, 5.41198724e-04, 9.92485137e-04, 3.26989085e-03,
       3.79581398e-03, 6.02486929e-04, 1.83369412e-03, 2.25763555e-04,
       1.02056452e-03, 1.56746276e-02, 8.57713159e-04, 7.13920166e-04,
       5.93224922e-04, 1.61010073e-04, 5.15336085e-04, 3.01744335e-04,
       1.25565059e-03, 1.29177507e-04, 2.47032845e-03, 1.08374188e-02,
       2.78603073e-04, 1.91752744e-04, 1.42589682e-03, 1.84889978e-03,
       1.27228245e-03, 2.64192705e-05, 3.43349346e-03, 1.08811561e-03,
       3.02519780e-03, 9.16721286e-04, 1.52733676e-03, 5.73499679e-04,
       1.55438345e-03, 1.02394923e-03, 1.51846517e-03, 2.25708089e-03,
       3.13597691e-04, 1.55235092e-03, 1.54242839e-03, 7.07565191e-04,
       1.78641716e-03, 3.03548262e-03, 5.70911413e-04, 2.26323935e-03,
       3.52971542e-04, 1.71431397e-03, 1.46409884e-03, 2.54501945e-03,
       2.26468561e-03, 1.52403311e-04, 1.22733222e-03, 4.50742552e-03,
       9.11376511e-04, 1.36672028e-03, 2.98370075e-04, 3.50236203e-04,
       8.16628860e-04, 8.41134581e-04, 2.95055816e-04, 5.05630767e-04,
       5.89463725e-04, 3.21128109e-04, 9.55952010e-04, 2.40200381e-03,
       8.94206606e-03, 9.58227615e-04, 5.61367492e-04, 4.74300193e-04,
       9.63035106e-04, 2.96597173e-03, 2.54917363e-04, 4.58469443e-04,
       2.43472960e-04, 5.86983028e-03, 3.05677621e-03, 5.14909240e-04,
       1.46821060e-03, 1.59801320e-03, 2.72486804e-03, 4.40968495e-03,
       9.90435803e-04, 2.61499117e-03, 9.15516674e-04, 1.41334890e-03,
       4.40139704e-03, 1.29117982e-03, 2.82467919e-04, 2.69980537e-03,
       4.53419245e-03, 2.74424067e-03, 7.03376978e-03, 1.24860274e-03,
       8.12118634e-05, 1.43804512e-03, 5.41440763e-04, 1.83289983e-02,
       1.59766791e-03, 1.52597219e-04, 2.62965081e-03, 4.58242900e-03,
       1.97456885e-03, 5.58792841e-03, 3.89632827e-03, 5.67154487e-03,
       1.49837453e-03, 3.50119739e-04, 5.99360716e-04, 3.17758965e-04,
       3.85472308e-04, 9.79400922e-04, 2.16366404e-03, 5.40912278e-04,
       1.20454041e-03, 1.14166564e-02, 7.16205030e-03, 9.12734451e-04,
       6.90694612e-04, 6.50817761e-05, 4.94270173e-04, 1.21474700e-03,
       5.59227218e-03, 1.15896251e-03, 1.00054064e-03, 2.21951372e-03,
       1.20472444e-03, 1.87914342e-03, 3.58597659e-04, 3.26956721e-03,
       6.93919533e-03, 3.73277821e-03, 2.80685616e-03, 3.53496769e-03,
       3.39679884e-03, 3.95464581e-03, 8.37353543e-04, 4.72412185e-04,
       3.33819288e-04, 4.26646639e-04, 1.26809750e-04, 2.31753766e-03,
       2.88880427e-03, 4.90411014e-04, 9.19809255e-04, 1.91789426e-03,
       7.55517559e-04, 1.00975375e-04, 1.64985979e-03, 5.19548399e-04,
       2.20051926e-03, 3.01923615e-03, 1.51316232e-03, 6.33893591e-03,
       3.80866136e-03, 5.60568450e-04, 9.78066169e-04, 2.51453570e-03,
       4.61889020e-03, 1.39267713e-03, 1.61020234e-04, 7.10216492e-04,
       2.58661364e-04, 4.64997095e-04, 2.37636093e-03, 1.92367516e-04,
       1.08174988e-03, 1.61723865e-03, 9.15541860e-04, 4.34093967e-03,
       3.74973070e-03, 1.22300780e-03, 1.50691643e-02, 3.43398623e-03,
       1.26283299e-03, 1.00558001e-02, 1.07777890e-03, 1.15220620e-02,
       1.41535884e-03, 1.42822833e-03, 4.62818782e-02, 6.44846334e-03,
       4.50347991e-04, 3.44973848e-03, 2.19898641e-04, 2.39150939e-03,
       9.48997849e-03, 1.92250664e-03, 8.86349229e-04, 5.54818351e-03,
       6.10807272e-03, 2.33017515e-03, 6.27339883e-03, 1.34897948e-02,
       4.03052109e-04, 1.03489687e-03, 2.03334932e-03, 8.35544816e-04,
       4.48272466e-03, 8.04465706e-03, 3.49081508e-03, 1.16854672e-04,
       8.81257255e-04, 1.01264116e-03, 1.39264201e-03, 2.02839598e-03,
       1.66451025e-04, 1.37186978e-03, 8.67760570e-04, 2.55284403e-04,
       2.77964732e-03, 1.92811868e-03, 1.04627287e-03, 1.26773640e-03,
       2.19787057e-04, 1.63003996e-03, 3.98348210e-04, 7.54053985e-04,
       9.01350963e-04, 1.55560144e-03, 3.79677302e-04, 1.70503275e-03,
       2.08445646e-03, 5.82908860e-03, 8.28022099e-03, 2.72287861e-03,
       7.56658201e-04, 3.09325460e-03, 1.43221602e-03, 2.65366883e-03,
       7.57457968e-03, 3.28001364e-03, 2.27869712e-04, 7.26900485e-04,
       1.34683978e-03, 2.44399326e-03, 1.12093095e-03, 8.35039520e-03,
       2.52429704e-04, 3.98556965e-04, 1.58847490e-03, 8.62263353e-03,
       2.24404638e-03, 7.46149828e-04, 8.20468871e-04, 1.44816185e-03,
       4.58540847e-03, 2.36880387e-03, 2.03954143e-04, 1.86907496e-03,
       2.31164922e-03, 6.03339406e-04, 1.59920218e-03, 2.89906519e-04,
       2.11304796e-03, 1.56312613e-03, 3.55753728e-03, 1.10317183e-02,
       4.63999731e-04, 1.19366851e-03, 1.71909883e-02, 1.48036825e-03,
       1.73668835e-03, 3.00633065e-03, 1.06743687e-03, 2.69664310e-03,
       9.60423949e-04, 3.87047329e-05, 2.65301712e-04, 6.29840289e-04,
       1.85184713e-02, 1.51958313e-03, 1.70847403e-03, 5.06453249e-04,
       2.21910769e-03, 4.56210118e-04, 1.66886918e-03, 2.97351298e-03,
       1.17067632e-02, 6.50128241e-03, 3.11012341e-03, 1.05467530e-02,
       2.03405790e-03, 3.29204249e-03, 2.54215010e-04, 1.23577354e-02,
       4.50482336e-05, 2.07231343e-03, 4.23478417e-04, 5.58816637e-04,
       1.71680039e-03, 1.22138993e-03, 6.82397907e-03, 3.98834802e-03,
       1.34244009e-03, 4.05895776e-03, 2.63302869e-03, 3.72844127e-04,
       1.56955732e-04, 5.19758419e-04, 1.47431394e-03, 9.30609431e-05,
       2.41906731e-03, 9.10164376e-03, 1.40461883e-03, 3.25622978e-04,
       3.80182735e-03, 7.22959649e-04, 1.16166705e-04, 2.11745690e-03,
       6.71440049e-04, 3.06508623e-03, 1.45704248e-03, 8.43005981e-04,
       2.21434873e-03, 8.76791123e-04, 9.62020442e-04, 9.25570407e-05,
       1.67725292e-03, 9.99564115e-04, 2.76527067e-03, 1.68072434e-03,
       2.38531702e-03, 1.29183305e-04, 4.85804670e-04])

In [151]:
weights

Ticker
ABT     0.000596
ACN     0.004519
ADI     0.006712
ADP     0.004832
ADSK    0.001468
          ...
XYL     0.002765
YUM     0.001681
ZBH     0.002385
ZG      0.000129
ZION    0.000486
Name: Weight, Length: 391, dtype: float64

In [145]:
print(weights.index.equals(covariance.columns))

True

In [154]:
w = weights.reindex(covariance.columns)

In [160]:
np.dot(np.dot(w, covariance), w)

nan

In [161]:
portfolio_variance = np.matmul(np.matmul(w, covariance), w)

portfolio_variance

In [ ]:
print(w.isna().sum())
print(covariance.isna().sum().sum())

0
781

In [168]:
nan_tickers = covariance.columns[covariance.isna().any()]
print(nan_tickers)

Index(['ABT', 'ACN', 'ADI', 'ADP', 'ADSK', 'AEP', 'AER', 'AES', 'AFL', 'AIG',
       ...
       'WMT', 'WST', 'WY', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBH', 'ZG', 'ZION'],
      dtype='object', length=391)

In [167]:
covariance[covariance.isna().any(axis=1)]

,ABT,ACN,ADI,ADP,ADSK,AEP,AER,AES,AFL,AIG,...,WMT,WST,WY,WYNN,XEL,XYL,YUM,ZBH,ZG,ZION
ABT,0.000199,0.000089,0.000072,0.000081,0.000097,0.000062,0.000071,0.000071,0.000060,0.000065,...,0.000042,0.000100,0.000081,0.000062,0.000060,0.000079,0.000067,0.000098,0.000094,0.000080
ACN,0.000089,0.000372,0.000131,0.000153,0.000226,0.000035,0.000119,0.000099,0.000081,0.000100,...,0.000046,0.000132,0.000109,0.000143,0.000042,0.000121,0.000077,0.000085,0.000197,0.000149
ADI,0.000072,0.000131,0.000448,0.000092,0.000199,0.000025,0.000202,0.000155,0.000070,0.000105,...,0.000051,0.000140,0.000143,0.000232,0.000032,0.000171,0.000084,0.000102,0.000222,0.000205
ADP,0.000081,0.000153,0.000092,0.000200,0.000158,0.000051,0.000075,0.000075,0.000080,0.000089,...,0.000045,0.000095,0.000085,0.000089,0.000054,0.000095,0.000070,0.000076,0.000145,0.000123
ADSK,0.000097,0.000226,0.000199,0.000158,0.000503,0.000025,0.000163,0.000131,0.000075,0.000105,...,0.000062,0.000163,0.000130,0.000215,0.000035,0.000160,0.000092,0.000105,0.000362,0.000182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XYL,0.000079,0.000121,0.000171,0.000095,0.000160,0.000056,0.000147,0.000142,0.000085,0.000110,...,0.000054,0.000113,0.000123,0.000148,0.000054,0.000273,0.000082,0.000100,0.000206,0.000168
YUM,0.000067,0.000077,0.000084,0.000070,0.000092,0.000053,0.000086,0.000095,0.000066,0.000078,...,0.000048,0.000074,0.000083,0.000097,0.000052,0.000082,0.000169,0.000071,0.000110,0.000071
ZBH,0.000098,0.000085,0.000102,0.000076,0.000105,0.000058,0.000111,0.000105,0.000070,0.000099,...,0.000039,0.000094,0.000106,0.000113,0.000058,0.000100,0.000071,0.000296,0.000117,0.000118
ZG,0.000094,0.000197,0.000222,0.000145,0.000362,0.000031,0.000193,0.000190,0.000055,0.000099,...,0.000045,0.000191,0.000185,0.000307,0.000041,0.000206,0.000110,0.000117,0.001096,0.000229
ZION,0.000080,0.000149,0.000205,0.000123,0.000182,0.000046,0.000247,0.000179,0.000160,0.000245,...,0.000047,0.000104,0.000184,0.000250,0.000047,0.000168,0.000071,0.000118,0.000229,0.000731

In [166]:
covariance.isna

<bound method DataFrame.isna of            ABT       ACN       ADI       ADP      ADSK       AEP       AER  \
ABT   0.000199  0.000089  0.000072  0.000081  0.000097  0.000062  0.000071
ACN   0.000089  0.000372  0.000131  0.000153  0.000226  0.000035  0.000119
ADI   0.000072  0.000131  0.000448  0.000092  0.000199  0.000025  0.000202
ADP   0.000081  0.000153  0.000092  0.000200  0.000158  0.000051  0.000075
ADSK  0.000097  0.000226  0.000199  0.000158  0.000503  0.000025  0.000163
...        ...       ...       ...       ...       ...       ...       ...
XYL   0.000079  0.000121  0.000171  0.000095  0.000160  0.000056  0.000147
YUM   0.000067  0.000077  0.000084  0.000070  0.000092  0.000053  0.000086
ZBH   0.000098  0.000085  0.000102  0.000076  0.000105  0.000058  0.000111
ZG    0.000094  0.000197  0.000222  0.000145  0.000362  0.000031  0.000193
ZION  0.000080  0.000149  0.000205  0.000123  0.000182  0.000046  0.000247

           AES       AFL       AIG  ...       WMT       WST        WY  \
ABT   0.000071  0.000060  0.000065  ...  0.000042  0.000100  0.000081
ACN   0.000099  0.000081  0.000100  ...  0.000046  0.000132  0.000109
ADI   0.000155  0.000070  0.000105  ...  0.000051  0.000140  0.000143
ADP   0.000075  0.000080  0.000089  ...  0.000045  0.000095  0.000085
ADSK  0.000131  0.000075  0.000105  ...  0.000062  0.000163  0.000130
...        ...       ...       ...  ...       ...       ...       ...
XYL   0.000142  0.000085  0.000110  ...  0.000054  0.000113  0.000123
YUM   0.000095  0.000066  0.000078  ...  0.000048  0.000074  0.000083
ZBH   0.000105  0.000070  0.000099  ...  0.000039  0.000094  0.000106
ZG    0.000190  0.000055  0.000099  ...  0.000045  0.000191  0.000185
ZION  0.000179  0.000160  0.000245  ...  0.000047  0.000104  0.000184

          WYNN       XEL       XYL       YUM       ZBH        ZG      ZION
ABT   0.000062  0.000060  0.000079  0.000067  0.000098  0.000094  0.000080
ACN   0.000143  0.000042  0.000121  0.000077  0.000085  0.000197  0.000149
ADI   0.000232  0.000032  0.000171  0.000084  0.000102  0.000222  0.000205
ADP   0.000089  0.000054  0.000095  0.000070  0.000076  0.000145  0.000123
ADSK  0.000215  0.000035  0.000160  0.000092  0.000105  0.000362  0.000182
...        ...       ...       ...       ...       ...       ...       ...
XYL   0.000148  0.000054  0.000273  0.000082  0.000100  0.000206  0.000168
YUM   0.000097  0.000052  0.000082  0.000169  0.000071  0.000110  0.000071
ZBH   0.000113  0.000058  0.000100  0.000071  0.000296  0.000117  0.000118
ZG    0.000307  0.000041  0.000206  0.000110  0.000117  0.001096  0.000229
ZION  0.000250  0.000047  0.000168  0.000071  0.000118  0.000229  0.000731

[391 rows x 391 columns]>